spring.application.name=interview
server.port=1212
spring.datasource.url=jdbc:mysql://localhost:3306/interview_db
spring.datasource.username=root
spring.datasource.password=bca123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
